CREATE TABLE `user_feedback`
(
    `id`         BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_id`    BIGINT NOT NULL,
    `rate`       INT,
    `content`    VARCHAR(128),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
