name: development-ci
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: 'gradle'

      - name: grant permission to gradle
        run: chmod +x gradlew

      - name: touch .env family
        run: |
          touch .env.dev
          echo "${{ secrets.ENV_DEV }}" > .env.dev
          touch .env.test
          echo "${{ secrets.ENV_DEV }}" > .env.test
        shell: bash

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: touch dev data.sql
        run: |
          touch src/main/resources/sql/data.sql
          echo "${{ secrets.DATA_SQL }}" > src/main/resources/sql/data.sql
        shell: bash

      - name: touch test data.sql
        run: |
          touch src/test/resources/sql/data.sql
          echo "${{ secrets.TEST_DATA_SQL }}" > src/test/resources/sql/data.sql
        shell: bash

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info

      - name: Upload Gradle Report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: gradle-report
          path: build/reports

      - name: Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ Backend CI failed ❗️
          webhook: ${{ secrets.DISCORD_URL }}
          color: FF0000
